### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice

### ISSUE THREAD

**Issue by ronyuzhang** [pgtgrly/U-Net-Pytorch#1]
i train my own data by using your checkpoint  of checkpoint_unets , but have a error "AttributeError: module 'torch._C' has no attribute '_cuda_getDevice".
 i train unet on cpu enviroment.

**Comment by pgtgrly** [comment]
I have made some changes, Can you pull the repository and test again? Please update me if it works or not.

**Comment by pgtgrly** [comment]
Closing as the issue is resolved

**Comment by xiaoguo1995** [comment]
Hi, @pgtgrly 

I face the same problem when I re-produce another code when I loading the .pt files.

I have no Nvidia GPU and run on a cpu only computer

Could you please share how you fix the **"module 'torch._C' has no attribute '_cuda_getDevice"** problem? Thank you very much!

Best,
Xiao

**Comment by pgtgrly** [comment]
Hey @PeterXiaoGuo 
To load the GPU trained weights to CPU you will have to map them. This can be done by simply loading the model using:

model=torch.load(trained_model.pt,map_location={'cuda:0': 'cpu'})

You can find the same in my code [here](https://github.com/pgtgrly/U-Net-Derived-Pytorch/blob/69f0df28eb141d9e274cd49bd7961e23b8c88283/api.py#L23)

Hope this helps.
Regards
PG

**Comment by xiaoguo1995** [comment]
Hey, @pgtgrly 
Thank you very much!!! 
I made it! Thank you !

Best,
Xiao

**Comment by pgtgrly** [comment]
@PeterXiaoGuo,
I am glad that I could help :)
Good Luck
PG

**Comment by ZangChaoyu** [comment]
我有GPU ，怎样解决呢请问
