### ISSUE TITLE
What is the use of sigmoid on the network? 

### ISSUE THREAD

**Issue by lidaryani** [pgtgrly/U-Net-Pytorch#2]
hi , I read your code and it was very useful to me, but in the main article that was provided for the u-net network, there was no mention of the use of sigmoid on the network. Please explain why you used it in the last layer of u-net network.
Thank you

**Comment by pgtgrly** [comment]
I am glad that you found it useful.  Again this network is a derivation for UNet. The reason why I specifically went for Sigmoid in the last layer was to bound the output between 0 and 1 (which will give us a normalized grayscale mask), this was to avoid post-processing errors with other activations (like ReLu in which case you would have to threshold outputs greater than 1).

**Comment by lidaryani** [comment]
> I am glad that you found it useful. Again this network is a derivation for UNet. The reason why I specifically went for Sigmoid in the last layer was to bound the output between 0 and 1 (which will give us a normalized grayscale mask), this was to avoid post-processing errors with other activations (like ReLu in which case you would have to threshold outputs greater than 1).

Thank you for your clear answer.
